### ISSUE TITLE
quality.QualityBRISQUE: (-215:Assertion failed) m.dims >= 2 in function 'Mat'

### ISSUE THREAD

**Issue by ndujar** [opencv/opencv_contrib#2343]
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Ubuntu 18.04 (bionic)
- Compiler => python3 binaries

##### Detailed description

When trying to execute the examples provided in the [documentation](https://github.com/opencv/opencv_contrib/tree/master/modules/quality), it fails with the following error:
```
cv2.error: OpenCV(4.1.1) /io/opencv/modules/core/src/matrix.cpp:406: error: (-215:Assertion failed) m.dims >= 2 in function 'Mat'
```
##### Steps to reproduce
```
This is my code:

import cv2
import numpy as np
cap = cv2.VideoCapture('../stream/144p/1HWSFYQXa1Q.mp4')

print(cap.get(cv2.CAP_PROP_FRAME_COUNT))
print(cap.get(cv2.CAP_PROP_FPS))
print(cap.get(cv2.CAP_PROP_BACKEND))

range_path = 'brisque_params/range_model_live.yml'
model_path = 'brisque_params/brisque_model_live.yml'

while cap.isOpened():
    ret, frame = cap.read()
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    frame = np.uint8(frame)

    score = cv2.quality.QualityBRISQUE_compute(frame, model_path, range_path)
     
    print(score)
    if not ret:
        break
    ```
The prints at the beginning return sensible values, and the frames are there because cv2.imwrite outputs the frame to my file system.

Any help would be very much appreciated

**Comment by alalek** [comment]
> if not ret:

This check must be performed earlier.

**Comment by ndujar** [comment]
> > if not ret:
> 
> This check must be performed earlier.

Thanks for the quick response.
However, this option was previously explored. The following code also returns the same error:

video_parser_opencv.py
```
cap = cv2.VideoCapture('../stream/144p/1HWSFYQXa1Q.mp4')

print(cap.get(cv2.CAP_PROP_FRAME_COUNT))
print(cap.get(cv2.CAP_PROP_FPS))
print(cap.get(cv2.CAP_PROP_BACKEND))

range_path = 'brisque_params/range_model_live.yml'
model_path = 'brisque_params/brisque_model_live.yml'

start_time = time.time()

while cap.isOpened():
    ret, frame = cap.read()
    if ret:
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        frame = np.uint8(frame)
        score = cv2.quality.QualityBRISQUE_compute(frame, model_path, range_path)
        frame_list.append(score)
        print(len(frame_list))
        print(score)
    else:
        break
print('Elapsed time:', time.time() - start_time)
```

outputs:

```
300.0
30.0
1900.0
Traceback (most recent call last):
  File "video_parser_opencv.py", line 155, in <module>
    score = cv2.quality.QualityBRISQUE_compute(frame, model_path, range_path)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/core/src/matrix.cpp:406: error: (-215:Assertion failed) m.dims >= 2 in function 'Mat'
```

Any other ideas?
Thanks in advance

**Comment by alalek** [comment]
There is common mistake - provided sample is not **minimal** (part with VideoCapture must be dropped, especially due missing input data).

Can't reproduce with current "master":
```
img = np.zeros((480, 640), np.uint8)
print(img.shape)
print(cv.utils.dumpInputArray(img))
res = cv.quality.QualityBRISQUE_compute(img, basedir + 'brisque_model_live.yml', basedir + 'brisque_range_live.yml')
print(res)
```

```
(480, 640)
InputArray: empty()=false kind=0x00010000 flags=0x01010000 total(-1)=307200 dims(-1)=2 size(-1)=640x480 type(-1)=CV_8UC1
(0.0, 0.0, 0.0, 0.0)
```

Use `cv.utils.dumpInputArray(frame)` to inspect content of passed values.

**Comment by ndujar** [comment]
Thanks again, but problems seems to be somewhere else.
This is my output when adapting your code:

Input:
```
range_path = 'brisque_params/range_model_live.yml'
model_path = 'brisque_params/brisque_model_live.yml'

img = np.zeros((480, 640), np.uint8)
print(img.shape)
print(cv2.utils.dumpInputArray(img))
res = cv2.quality.QualityBRISQUE_compute(img, model_path, range_path)
print(res)
```
Output:
```
(480, 640)
InputArray: empty()=false kind=0x00010000 flags=0x01010000 total(-1)=307200 dims(-1)=2 size(-1)=640x480 type(-1)=CV_8UC1
Traceback (most recent call last):
  File "video_parser_opencv.py", line 162, in <module>
    res = cv2.quality.QualityBRISQUE_compute(img, model_path, range_path)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/core/src/matrix.cpp:406: error: (-215:Assertion failed) m.dims >= 2 in function 'Mat'
```

**Comment by alalek** [comment]
>  model_path, range_path

Double check these:

```
print(os.path.exists(model_path))
print(os.path.exists(range_path))
```

**Comment by ndujar** [comment]
Thank you very much again. This fixed the problem.
Path to brisque_range.yml was wrongly assigned. My fault :/
This is the code:

```
range_path = 'brisque_params/brisque_range.yml'
model_path = 'brisque_params/brisque_model_live.yml'

cap=cv2.VideoCapture('../stream/sources/vimeo/104681073-no-audio.mp4')

start_time = time.time()
i = 0
while cap.isOpened():
    ret, frame = cap.read()
    if ret:
        i += 1
        res = cv2.quality.QualityBRISQUE_compute(frame, model_path, range_path)
        print(i, res)
    else:
        break

print('Elapsed time:', time.time() - start_time)
```

Now it outputs:
```
1 (103.02975463867188, 0.0, 0.0, 0.0)
2 (109.54379272460938, 0.0, 0.0, 0.0)
3 (109.88373565673828, 0.0, 0.0, 0.0)
4 (109.19992065429688, 0.0, 0.0, 0.0)
5 (108.17030334472656, 0.0, 0.0, 0.0)
6 (106.07408142089844, 0.0, 0.0, 0.0)
...
265 (111.05577850341797, 0.0, 0.0, 0.0)
266 (112.9259033203125, 0.0, 0.0, 0.0)
267 (112.94620513916016, 0.0, 0.0, 0.0)
268 (75.07886505126953, 0.0, 0.0, 0.0)
Elapsed time: 28.301172733306885
```
