### ISSUE TITLE
Java UnsatisfiedLinkError for Contrib Modules

### ISSUE THREAD

**Issue by MarcusDunn** [opencv/opencv_contrib#2534]
##### System information (version)

- OpenCV => 4.3
- Operating System / Platform => Ubuntu 18.04
- Compiler => GCC
- Java Version => 8

##### Detailed description

I've got a small OpenCV project in java that works fine with all of the non-contrib modules. However, I'm currently attempting to add the dnn-superres to the project and despite recompiling without issue with dnn-superres enabled. the Jar produced contains the classes, but at runtime it throws the following error apon the first call to the dnn-superres classes. 
```
java.lang.UnsatisfiedLinkError: org.opencv.dnn_superres.DnnSuperResImpl.create_0()J
	at org.opencv.dnn_superres.DnnSuperResImpl.create_0(Native Method) ~[opencv-430.jar:4.3.0-201-gc722625f28]
	at org.opencv.dnn_superres.DnnSuperResImpl.create(DnnSuperResImpl.java:52) ~[opencv-430.jar:4.3.0-201-gc722625f28]
```
The problem persists with other contib modules (I tested with face and xfeatures2d). This seems to be the same error as https://github.com/opencv/opencv_contrib/issues/2054.

##### Steps to reproduce

- in opencv_contrib/modules/dnn_superres/CMakeLists.txt add java to line 9:

    set(the_description "Super Resolution using CNNs")

    ocv_define_module(
        dnn_superres
        opencv_core
        opencv_imgproc
        opencv_dnn
        OPTIONAL opencv_quality
        WRAP python <ins> java </ins>
    )

(this is apparently needed and simply changing the makefile left the produced jar unchanged)

- compile OpenCV from source with java bindings and add dnn-superres as a target. 
[Makefile.zip](https://github.com/opencv/opencv_contrib/files/4636610/Makefile.zip) here is the makefile I created
- add the jar to the java project
- try to make calls to anything in the dnn-superres module 
```
System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
DnnSuperResImpl sr = DnnSuperResImpl.create();
```

**Comment by MarcusDunn** [comment]
Fixed by dumping literally all my .so files into usr/lib/
