### ISSUE TITLE
opencv-4.5.4/modules/dnn/src/dnn.cpp:916: error

### ISSUE THREAD

**Issue by sjtuzhaoxh** [opencv/opencv_contrib#3379]
org.opencv.core.CvException: cv::Exception: OpenCV(4.5.4) /opencv-4.5.4/modules/dnn/src/dnn.cpp:916: error: (-215:Assertion failed) mapIt != reuseMap.end() in function 'releaseReference'

        at org.opencv.wechat_qrcode.WeChatQRCode.detectAndDecode_1(Native Method)
        at org.opencv.wechat_qrcode.WeChatQRCode.detectAndDecode(WeChatQRCode.java:124)

----
org.opencv.core.CvException: cv::Exception: OpenCV(4.5.4) /opencv-4.5.4/modules/dnn/src/dnn.cpp:916: error: (-215:Assertion failed) mapIt != reuseMap.end() in function 'releaseReference'

        at org.opencv.wechat_qrcode.WeChatQRCode.detectAndDecode_1(Native Method)
        at org.opencv.wechat_qrcode.WeChatQRCode.detectAndDecode(WeChatQRCode.java:124)

linux, detect qrcode

**Comment by AlienWorldZ** [comment]
I meet the similar issue：Standard exception: OpenCV(4.8.0) D:\MySoftwares\opencv\opencv_contrib-4.x\modules\wechat_qrcode\src\wechat_qrcode.cpp:57: error: (-215:Assertion failed) utils::fs::exists(detector_prototxt_path) in function 'cv::wechat_qrcode::WeChatQRCode::WeChatQRCode'
