### ISSUE TITLE
[wechat_qrcode] crash， received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by bestlee666** [opencv/opencv_contrib#3570]
识别二维码时，崩溃
[QRCode][det] begin detector_->detectAndDecode, file=../images/cls/bus.jpg
![bus](https://github.com/opencv/opencv_contrib/assets/143471781/a06f0ef0-43c9-438d-a751-1721758ad08c)

Thread 1  received signal SIGSEGV, Segmentation fault.
0x00007ffff7a40928 in zxing::BitMatrix::get(int, int) const () from /usr/lib/libopencv_wechat_qrcode.so.407
(gdb) bt 
#0  0x00007ffff7a40928 in zxing::BitMatrix::get(int, int) const () from /usr/lib/libopencv_wechat_qrcode.so.407
#1  0x00007ffff7a40abb in zxing::qrcode::Detector::sizeOfBlackWhiteBlackRun(int, int, int, int) () from /usr/lib/libopencv_wechat_qrcode.so.407
#2  0x00007ffff7a40b7c in zxing::qrcode::Detector::sizeOfBlackWhiteBlackRunBothWays(int, int, int, int, int, bool) () from /usr/lib/libopencv_wechat_qrcode.so.407
#3  0x00007ffff7a40d90 in zxing::qrcode::Detector::calculateModuleSizeOneWay(zxing::Ref<zxing::ResultPoint>, zxing::Ref<zxing::ResultPoint>, int, int) ()
   from /usr/lib/libopencv_wechat_qrcode.so.407
#4  0x00007ffff7a43e99 in zxing::qrcode::Detector::processFinderPatternInfo(zxing::Ref<zxing::qrcode::FinderPatternInfo>, zxing::ErrorHandler&) ()
   from /usr/lib/libopencv_wechat_qrcode.so.407
#5  0x00007ffff7a44c7e in zxing::qrcode::Detector::getPossibleAlignmentCount(int) () from /usr/lib/libopencv_wechat_qrcode.so.407
#6  0x00007ffff7a4e9ef in zxing::qrcode::QRCodeReader::decodeMore(zxing::Ref<zxing::BinaryBitmap>, zxing::Ref<zxing::BitMatrix>, zxing::DecodeHints, zxing::ErrorHandler&) () from /usr/lib/libopencv_wechat_qrcode.so.407
#7  0x00007ffff7a4f88d in zxing::qrcode::QRCodeReader::decode(zxing::Ref<zxing::BinaryBitmap>, zxing::DecodeHints) () from /usr/lib/libopencv_wechat_qrcode.so.407
#8  0x00007ffff7a2ef21 in cv::wechat_qrcode::DecoderMgr::Decode(zxing::Ref<zxing::BinaryBitmap>, zxing::DecodeHints) () from /usr/lib/libopencv_wechat_qrcode.so.407
#9  0x00007ffff7a2f054 in cv::wechat_qrcode::DecoderMgr::TryDecode(zxing::Ref<zxing::LuminanceSource>, std::vector<zxing::Ref<zxing::Result>, std::allocator<zxing::Ref<zxing::Result> > >&) () from /usr/lib/libopencv_wechat_qrcode.so.407
#10 0x00007ffff7a2f7ca in cv::wechat_qrcode::DecoderMgr::decodeImage(cv::Mat, bool, std::vector<std::string, std::allocator<std::string> >&, std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > >&) ()
   from /usr/lib/libopencv_wechat_qrcode.so.407
#11 0x00007ffff7a3220d in cv::wechat_qrcode::WeChatQRCode::Impl::decode(cv::Mat const&, std::vector<cv::Mat, std::allocator<cv::Mat> >&, std::vector<cv::Mat, std::allocator<cv::Mat> >&) () from /usr/lib/libopencv_wechat_qrcode.so.407
#12 0x00007ffff7a328e7 in cv::wechat_qrcode::WeChatQRCode::detectAndDecode(cv::_InputArray const&, cv::_OutputArray const&) ()
   from /usr/lib/libopencv_wechat_qrcode.so.407

**Comment by opencv-alalek** [comment]
> libopencv_wechat_qrcode.so.407

You need to upgrade your OpenCV version first.

**Comment by lasthash** [comment]
My program encountered the same issue in version 4.8.0，how to solve it?
