### ISSUE TITLE
Error in Makefile2 copying Java file

### ISSUE THREAD

**Issue by cadencetech** [opencv/opencv_contrib#860]
- OpenCV => 3.1
- Operating System / Platform => Ubuntu 16.04 LTS - 64-bit
- Compiler => gcc-5.4.0

##### Detailed description

[ 91%] Generating src/org/opencv/bioinspired/Bioinspired.java
Error copying file (if different) from "/home/developer2/opencv-master/build/modules/java/gen/bioinspired+Bioinspired.java" to "/home/developer2/opencv-master/build/src/org/opencv/bioinspired/Bioinspired.java".
modules/java/CMakeFiles/opencv_java.dir/build.make:11261: recipe for target 'src/org/opencv/bioinspired/Bioinspired.java' failed
make[2]: *** [src/org/opencv/bioinspired/Bioinspired.java] Error 1
CMakeFiles/Makefile2:18526: recipe for target 'modules/java/CMakeFiles/opencv_java.dir/all' failed
make[1]: *** [modules/java/CMakeFiles/opencv_java.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
developer2@superquantan:~/opencv-master/build$

**Comment by mshabunin** [comment]
@cadencetech , please try to build latest master branch version.

**Comment by cadencetech** [comment]
It was built from the latest version of the master. Was this fixed within the last day or so?

**Comment by mshabunin** [comment]
We can not reproduce it, please try to make clean build and add more information (cmake output).

**Comment by cadencetech** [comment]
Thanks. Cleared the build directory and it compiled without errors.

**Comment by Ivan-Guillermo-Duarte** [comment]
Good Afternoon, could help me with this error, I thank you very much.

[ 80%] Generating src/org/opencv/imgproc/Moments.java
[ 80%] Generating opencv-310.jar
/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/rt.jar: inflateFully: Unexpected end of strea

BUILD FAILED
java.lang.NoClassDefFoundError: java/math/BigInteger
        at org.apache.tools.ant.types.Resource.getMagicNumber(Resource.java:58)
        at org.apache.tools.ant.types.Resource.<clinit>(Resource.java:48)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:90)
        at org.apache.tools.ant.Main.runBuild(Main.java:826)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.ClassNotFoundException: java.math.BigInteger
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 7 more

Total time: 0 seconds
java.lang.NoClassDefFoundError: java/math/BigInteger
        at org.apache.tools.ant.types.Resource.getMagicNumber(Resource.java:58)
        at org.apache.tools.ant.types.Resource.<clinit>(Resource.java:48)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:90)
        at org.apache.tools.ant.Main.runBuild(Main.java:826)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.ClassNotFoundException: java.math.BigInteger
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 7 more
java/math/BigInteger
modules/java/CMakeFiles/opencv_java.dir/build.make:11280: recipe for target 'bin/opencv
make[2]: *** [bin/opencv-310.jar] Error 1
CMakeFiles/Makefile2:6458: recipe for target 'modules/java/CMakeFiles/opencv_java.dir/a
make[1]: *** [modules/java/CMakeFiles/opencv_java.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fcemtopall** [comment]
91% of the time after the make command I get this error what can I do?

[ 91%] Generate files for Java bindings
Traceback (most recent call last):
  File "/home/fcemtopall/Masaüstü/opencv-3.4.1/modules/java/generator/../generator/gen_java.py", line 1093, in <module>
    copy_java_files(java_files_dir, target_path)
  File "/home/fcemtopall/Masaüstü/opencv-3.4.1/modules/java/generator/../generator/gen_java.py", line 1032, in copy_java_files
    src = checkFileRemap(java_file)
  File "/home/fcemtopall/Masaüstü/opencv-3.4.1/modules/java/generator/../generator/gen_java.py", line 25, in checkFileRemap
    assert path[-3:] != '.in', path
AssertionError: /home/fcemtopall/Masaüstü/opencv-3.4.1/modules/java/generator/src/java/org/opencv/osgi/OpenCVNativeLoader.java.in
modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/build.make:315: recipe for target 'CMakeFiles/dephelper/gen_opencv_java_source' failed
make[2]: *** [CMakeFiles/dephelper/gen_opencv_java_source] Error 1
CMakeFiles/Makefile2:2686: recipe for target 'modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/all' failed
make[1]: *** [modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alalek** [comment]
@fcemtopall This is correct issue for your problem: https://github.com/opencv/opencv/issues/11153

I will remove your comment because it is not related to the original problem (it is about OpenCV 3.1).
